# Generated by Django 3.2.21 on 2023-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('Password', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'port_user',
            },
        ),
    ]
