# Generated by Django 3.2.21 on 2023-09-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port_user',
        ),
    ]
