# Generated by Django 3.2.21 on 2023-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
