# Generated by Django 3.2.21 on 2023-09-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0004_auto_20230922_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfeil',
            new_name='UserProfile',
        ),
    ]
