# Generated by Django 3.2.21 on 2023-09-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0005_rename_userprofeil_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
