# Generated by Django 3.2.21 on 2023-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0006_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
    ]
