# Generated by Django 3.2.21 on 2023-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0007_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(default='default_profile_image.jpg', upload_to=''),
        ),
    ]
