# Generated by Django 3.2.21 on 2023-10-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPort', '0009_auto_20231006_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
